version: "3.7"

services:
  api:
    image: bedrockio/tectonic-api:latest
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "yarn",
        "start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR=false
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    ports:
      - "3300:3300"
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch

  cli:
    image: bedrockio/tectonic-cli:latest
    command: bash -c "./scripts/wait-for-it.sh mongo:27017 && ./scripts/wait-for-it.sh elasticsearch:9200 && sleep 10 && node ./scripts/publish-fixture-events.js"
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR=false
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
      - API_URL=http://api:3300
    links:
      - api
      - mongo
      - elasticsearch
    depends_on:
      - api
      - mongo
      - elasticsearch

  web:
    image: bedrockio/tectonic-web:latest
    command: ["yarn", "start"]
    ports:
      - "3200:3200"
    depends_on:
      - api

  mongo:
    image: mongo:5.0.2
    logging:
      driver: none
    ports:
      - 27017

  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - 9200
      - 9300
    environment:
      - "discovery.type=single-node"
      - "logger.level=WARN"
