version: "3.7"

services:
  api:
    image: bedrockio/tectonic-api:latest
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "./scripts/wait-for-it.sh",
        "pubsub:9200",
        "--",
        "yarn",
        "start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR_HOST=pubsub:8200
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    ports:
      - "3300:3300"
    links:
      - mongo
      - pubsub
      - elasticsearch
      - elasticsearch-sink
    depends_on:
      - mongo
      - pubsub
      - elasticsearch
      - elasticsearch-sink

  cli:
    image: bedrockio/tectonic-cli:latest
    command: bash -c "./scripts/wait-for-it.sh mongo:27017 && ./scripts/wait-for-it.sh elasticsearch:9200 && ./scripts/wait-for-it.sh pubsub:8200 && sleep 20 && node ./scripts/publish-fixture-events.js"
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR_HOST=pubsub:8200
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
      - API_URL=http://api:3300
    links:
      - api
      - mongo
      - pubsub
      - elasticsearch
      - elasticsearch-sink
    depends_on:
      - api
      - mongo
      - pubsub
      - elasticsearch
      - elasticsearch-sink

  elasticsearch-sink:
    image: bedrockio/tectonic-elasticsearch-sink:latest
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "./scripts/wait-for-it.sh",
        "pubsub:9200",
        "--",
        "yarn",
        "elasticsearch-sink:start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR_HOST=pubsub:8200
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    links:
      - mongo
      - pubsub
      - elasticsearch
    depends_on:
      - mongo
      - pubsub
      - elasticsearch

  web:
    image: bedrockio/tectonic-web:latest
    command: ["yarn", "start"]
    ports:
      - "3200:3200"
    depends_on:
      - api

  mongo:
    image: mongo:5.0.1
    command: --serviceExecutor adaptive
    logging:
      driver: none
    ports:
      - 27017

  pubsub:
    image: bedrockio/tectonic-pubsub-emulator:latest
    ports:
      - 8200

  elasticsearch:
    image: elasticsearch:7.12.0
    ports:
      - 9200
      - 9300
    environment:
      - "discovery.type=single-node"
