apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tectonic-web-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: tectonic-web-ingress
spec:
  defaultBackend:
    service:
      name: web-nodeport
      port:
        number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  labels:
    name: web-nodeport
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3200
      protocol: TCP
