apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: bedrockio/tectonic-web:<TECTONIC_VERSION>
          imagePullPolicy: Always
          name: main
          env:
            - name: ENV_NAME
              value: <ENV_NAME>
            - name: NODE_ENV
              value: production
            - name: API_URL
              value: <API_URL>
          ports:
            - name: http-server
              containerPort: 3200
